{{- if .Values.storage.sharedVolume.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "auralith-data-pipeline.fullname" . }}-data
  labels:
    {{- include "auralith-data-pipeline.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.storage.sharedVolume.accessMode }}
  storageClassName: {{ .Values.storage.sharedVolume.storageClass }}
  resources:
    requests:
      storage: {{ .Values.storage.sharedVolume.size }}
{{- end }}
